/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_posts` VALUES
(1,1,"2017-11-24 17:47:29","2017-11-24 17:47:29","Welcome to WordPress. This is your first post. Edit or delete it, then start writing!","Hello world!","","publish","open","open","","hello-world","","","2017-11-24 17:47:29","2017-11-24 17:47:29","",0,"http://spectrumbox.local/?p=1",0,"post","",1),
(2,1,"2017-11-24 17:47:29","2017-11-24 17:47:29","This is an example page. It\'s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:\n\n<blockquote>Hi there! I\'m a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like pi&#241;a coladas. (And gettin\' caught in the rain.)</blockquote>\n\n...or something like this:\n\n<blockquote>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</blockquote>\n\nAs a new WordPress user, you should go to <a href=\"http://spectrumbox.local/wp-admin/\">your dashboard</a> to delete this page and create new pages for your content. Have fun!","Sample Page","","publish","closed","open","","sample-page","","","2017-11-24 17:47:29","2017-11-24 17:47:29","",0,"http://spectrumbox.local/?page_id=2",0,"page","",0),
(3,1,"2017-11-24 17:56:19","0000-00-00 00:00:00","","Auto Draft","","auto-draft","open","open","","","","","2017-11-24 17:56:19","0000-00-00 00:00:00","",0,"http://spectrumbox.local/?p=3",0,"post","",0),
(4,1,"2017-11-24 20:59:29","2017-11-24 20:59:29","One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. \"What\'s happened to me?\" he thought. It wasn\'t a dream. His room, a proper human","Post 1","","publish","open","open","","post-1","","","2017-11-24 20:59:29","2017-11-24 20:59:29","",0,"http://spectrumbox.local/?p=4",0,"post","",0),
(5,1,"2017-11-24 20:59:29","2017-11-24 20:59:29","One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. \"What\'s happened to me?\" he thought. It wasn\'t a dream. His room, a proper human","Post 1","","inherit","closed","closed","","4-revision-v1","","","2017-11-24 20:59:29","2017-11-24 20:59:29","",4,"http://spectrumbox.local/index.php/2017/11/24/4-revision-v1/",0,"revision","",0),
(6,1,"2017-11-24 21:00:11","2017-11-24 21:00:11","But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally","Post 2","","publish","open","open","","post-2","","","2017-11-24 21:00:11","2017-11-24 21:00:11","",0,"http://spectrumbox.local/?p=6",0,"post","",0),
(7,1,"2017-11-24 21:00:11","2017-11-24 21:00:11","But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally","Post 2","","inherit","closed","closed","","6-revision-v1","","","2017-11-24 21:00:11","2017-11-24 21:00:11","",6,"http://spectrumbox.local/index.php/2017/11/24/6-revision-v1/",0,"revision","",0),
(8,1,"2017-11-24 21:00:35","2017-11-24 21:00:35","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with","Post 3","","publish","open","open","","post-3","","","2017-11-24 21:00:35","2017-11-24 21:00:35","",0,"http://spectrumbox.local/?p=8",0,"post","",0),
(9,1,"2017-11-24 21:00:35","2017-11-24 21:00:35","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with","Post 3","","inherit","closed","closed","","8-revision-v1","","","2017-11-24 21:00:35","2017-11-24 21:00:35","",8,"http://spectrumbox.local/index.php/2017/11/24/8-revision-v1/",0,"revision","",0);
